### ISSUE TITLE
跪求具体上的教程

### ISSUE THREAD

**Issue by laohanme** [CoderLinLee/LLSegmentViewController#1]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/18119268/52027206-7b1d4e00-2545-11e9-84a8-b8151a117a3a.png">

**Comment by CoderLinLee** [comment]
你这是运行的我的项目吗？

**Comment by laohanme** [comment]
是的 我再试试看

**Comment by CoderLinLee** [comment]
好的，如果还有其他问题可以向我提出，我会一直改进这个库
