### ISSUE TITLE
指示器固定的疑问

### ISSUE THREAD

**Issue by WS-Vincent** [CoderLinLee/LLSegmentViewController#2]
想让顶部指示器固定不跟随下拉滑动，有相应的开关变量控制吗

**Comment by CoderLinLee** [comment]
新年快乐，这几天一直在走亲戚，没关注这里了。
你可以在下拉的时候用这个方法 :public func relayoutSegmentControlAndPageViewFrame(segmentControlFrame:CGRect,pageViewFrame:CGRect) 实时调整控件布局。
或者你给出一个参考效果的app，我把这种效果加进去。

**Comment by WS-Vincent** [comment]
嗯 好的 谢谢 知道了
