### ISSUE TITLE
Crash on iOS 10.3.3 Device

### ISSUE THREAD

**Issue by cloudhm** [CoderLinLee/LLSegmentViewController#5]
2019-03-21 00:36:14.710 LLSegmentViewController[27670:907558] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x600000148f00 of class UITabBarItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x608000426140> (
<NSKeyValueObservance 0x600000244d70: Observer: 0x7fc7ea60b0d0, Key path: badgeValue, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000242f40>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108070b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000104e20141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001080d9625 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010495bb53 NSKVODeallocate + 294
	4   libobjc.A.dylib                     0x0000000104e34b8e _ZN11objc_object17sidetable_releaseEb + 202
	5   UIKit                               0x0000000105e00b13 -[UIViewController .cxx_destruct] + 913
	6   libobjc.A.dylib                     0x0000000104e1e9bc _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	7   libobjc.A.dylib                     0x0000000104e2ad34 objc_destructInstance + 129
	8   libobjc.A.dylib                     0x0000000104e2ad66 object_dispose + 22
	9   UIKit                               0x0000000105e4ea21 -[UIResponder dealloc] + 145
	10  UIKit                               0x0000000105dd8cca -[UIViewController dealloc] + 1846
	11  libswiftCore.dylib                  0x000000010779acfb swift_arrayDestroy + 59
	12  libswiftCore.dylib                  0x00000001075351e6 $Ss23_ContiguousArrayStorageCfD + 54
	13  libswiftCore.dylib                  0x00000001077a6910 _swift_release_dealloc + 16
	14  LLSegmentViewController             0x000000010463f2e0 $SSaySo16UIViewControllerCGWOh + 16
	15  libobjc.A.dylib                     0x0000000104e1e9bc _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
	16  libobjc.A.dylib                     0x0000000104e2ad34 objc_destructInstance + 129
	17  libobjc.A.dylib                     0x0000000104e2ad66 object_dispose + 22
	18  UIKit                               0x0000000105e4ea21 -[UIResponder dealloc] + 145
	19  UIKit                               0x0000000105cce318 -[UIView dealloc] + 1874
	20  LLSegmentViewController             0x000000010467903b $S23LLSegmentViewController18LLSegmentedControlCfD + 363
	21  LLSegmentViewController             0x0000000104679094 $S23LLSegmentViewController18LLSegmentedControlCfDTo + 36
	22  libobjc.A.dylib                     0x0000000104e352fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
	23  UIKit                               0x0000000105cce2f7 -[UIView dealloc] + 1841
	24  UIKit                               0x0000000105d08ef0 -[UIScrollView dealloc] + 833
	25  LLSegmentViewController             0x000000010462cf36 $S23LLSegmentViewController017LLContainerScrollB0CfD + 198
	26  LLSegmentViewController             0x000000010462d2d4 $S23LLSegmentViewController017LLContainerScrollB0CfDTo + 36
	27  Foundation                          0x000000010495ba8d NSKVODeallocate + 96
	28  libobjc.A.dylib                     0x0000000104e352fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
	29  UIKit                               0x0000000105cce2f7 -[UIView dealloc] + 1841
	30  libobjc.A.dylib                     0x0000000104e352fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
	31  CoreFoundation                      0x0000000107fbfe96 _CFAutoreleasePoolPop + 22
	32  CoreFoundation                      0x0000000107ffbaec __CFRunLoopRun + 2172
	33  CoreFoundation                      0x0000000107ffb016 CFRunLoopRunSpecific + 406
	34  GraphicsServices                    0x000000010ae57a24 GSEventRunModal + 62
	35  UIKit                               0x0000000105c39134 UIApplicationMain + 159
	36  LLSegmentViewController             0x000000010465af14 main + 68
	37  libdyld.dylib                       0x000000010964e65d start + 1
	38  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by CoderLinLee** [comment]
已经解决了，请下载最新版本
