### ISSUE TITLE
带headView

### ISSUE THREAD

**Issue by wsb0617** [CoderLinLee/LLSegmentViewController#7]
有系统的nav的时候，带headView无法滑动到顶部
class DVideoController:LLSegmentViewController{
}
DVideoController是tabbar上的第三个页面,带系统的导航栏的
    func layoutContentView() {
        
        hotPagerView.frame =  CGRect(x: 0, y:0, width: kScreenW, height: 104)
       self.layoutInfo.headView = hotPagerView
        
        self.layoutInfo.refreshType = .container
        self.layoutInfo.segmentControlPositionType = .top(size: CGSize.init(width: UIScreen.main.bounds.width, height: 40),offset:0)
        self.relayoutSubViews()
    }
请问是什么原因导致headview无法滑动到最底部一直有一个导航栏的高度无法滑动

**Comment by CoderLinLee** [comment]
不好意思，最近工作有点忙，没能及时回复。你能发个Demo连接吗，我这个用是没有问题的
